-- public.party definition

-- Drop table

-- DROP TABLE public.party;

CREATE TABLE public.party (
                              id uuid NOT NULL,
                              address_line1 varchar(255) NULL,
                              city varchar(255) NULL,
                              country varchar(255) NULL,
                              created_at timestamptz(6) NOT NULL,
                              email varchar(150) NULL,
                              first_name varchar(255) NULL,
                              golden_record bool NOT NULL,
                              last_name varchar(255) NULL,
                              merged_into_id uuid NULL,
                              organization_name varchar(255) NULL,
                              party_type varchar(20) NOT NULL,
                              phone varchar(30) NULL,
                              postal_code varchar(255) NULL,
                              state varchar(255) NULL,
                              status varchar(20) NOT NULL,
                              updated_at timestamptz(6) NOT NULL,
                              CONSTRAINT party_party_type_check CHECK (((party_type)::text = ANY ((ARRAY['INDIVIDUAL'::character varying, 'ORGANIZATION'::character varying])::text[]))),
	CONSTRAINT party_pkey PRIMARY KEY (id),
	CONSTRAINT party_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'MERGED'::character varying, 'INACTIVE'::character varying])::text[])))
);


-- public.source_system definition

-- Drop table

-- DROP TABLE public.source_system;

CREATE TABLE public.source_system (
                                      id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                      active bool NOT NULL,
                                      code varchar(30) NOT NULL,
                                      created_at timestamptz(6) DEFAULT now() NOT NULL,
                                      description varchar(500) NULL,
                                      "name" varchar(100) NOT NULL,
                                      CONSTRAINT source_system_pkey PRIMARY KEY (id),
                                      CONSTRAINT uk8i18h5s8f65kvr6ypil1w2jxl UNIQUE (code)
);


-- public.party_cross_reference definition

-- Drop table

-- DROP TABLE public.party_cross_reference;

CREATE TABLE public.party_cross_reference (
                                              id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                              last_synced_at timestamptz(6) NOT NULL,
                                              source_record_id varchar(100) NOT NULL,
                                              party_id uuid NOT NULL,
                                              source_system_id int8 NOT NULL,
                                              CONSTRAINT party_cross_reference_pkey PRIMARY KEY (id),
                                              CONSTRAINT uk86by45jjwg24rp273bui6sjw1 UNIQUE (source_system_id, source_record_id),
                                              CONSTRAINT fkhhu4yer91iwq6pkcrc4fgp4g9 FOREIGN KEY (source_system_id) REFERENCES public.source_system(id),
                                              CONSTRAINT fkk48wa17kk193goobu9qnc66kx FOREIGN KEY (party_id) REFERENCES public.party(id)
);


INSERT INTO public.source_system
(id, active, code, created_at, description, "name")
VALUES(0, false, '', now(), '', '');